version: '3'

services:
  php:
    build: 
      context: .infra/php
    image: otaodev/php:latest
    container_name: php
    volumes:
      - ./app:/var/www
    networks:
      - otaonet

  nginx:
    build: 
      context: .infra/nginx
    image: otaodev/nginx:latest
    container_name: nginx
    volumes:
      - ./app/public:/var/www/public:delegated
    networks:
      - otaonet
    ports:
      - "8080:80"

networks:
  otaonet:
    driver: bridge